/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {RoomCreated}
 */
// @ts-ignore
export function createRoomCreatedFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRoomCreated;
}
/**
 * The deserialization information for the current model
 * @param RoomCreated The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRoomCreated(roomCreated: Partial<RoomCreated> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { roomCreated.id = n.getStringValue(); },
    }
}
export interface RoomCreated extends AdditionalDataHolder, Parsable {
    /**
     * The id property
     */
    id?: string | null;
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param RoomCreated The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRoomCreated(writer: SerializationWriter, roomCreated: Partial<RoomCreated> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!roomCreated || isSerializingDerivedType) { return; }
    writer.writeStringValue("id", roomCreated.id);
    writer.writeAdditionalData(roomCreated.additionalData);
}
/* tslint:enable */
/* eslint-enable */
