/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createUntypedNodeFromDiscriminatorValue, type AdditionalDataHolder, type Parsable, type ParseNode, type SerializationWriter, type UntypedNode } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {RoomCounterUpdated}
 */
// @ts-ignore
export function createRoomCounterUpdatedFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRoomCounterUpdated;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {RoomCreated}
 */
// @ts-ignore
export function createRoomCreatedFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRoomCreated;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {RoomJoined}
 */
// @ts-ignore
export function createRoomJoinedFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRoomJoined;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {RoomJoinRequest}
 */
// @ts-ignore
export function createRoomJoinRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRoomJoinRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SignalRNegotiation}
 */
// @ts-ignore
export function createSignalRNegotiationFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSignalRNegotiation;
}
/**
 * The deserialization information for the current model
 * @param RoomCounterUpdated The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRoomCounterUpdated(roomCounterUpdated: Partial<RoomCounterUpdated> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "counter": n => { roomCounterUpdated.counter = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param RoomCreated The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRoomCreated(roomCreated: Partial<RoomCreated> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { roomCreated.id = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param RoomJoined The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRoomJoined(roomJoined: Partial<RoomJoined> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "counter": n => { roomJoined.counter = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param RoomJoinRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRoomJoinRequest(roomJoinRequest: Partial<RoomJoinRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "connectionId": n => { roomJoinRequest.connectionId = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param SignalRNegotiation The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSignalRNegotiation(signalRNegotiation: Partial<SignalRNegotiation> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "accessToken": n => { signalRNegotiation.accessToken = n.getStringValue(); },
        "url": n => { signalRNegotiation.url = n.getStringValue(); },
    }
}
export interface RoomCounterUpdated extends AdditionalDataHolder, Parsable {
    /**
     * The counter property
     */
    counter?: UntypedNode | null;
}
export interface RoomCreated extends AdditionalDataHolder, Parsable {
    /**
     * The id property
     */
    id?: string | null;
}
export interface RoomJoined extends AdditionalDataHolder, Parsable {
    /**
     * The counter property
     */
    counter?: UntypedNode | null;
}
export interface RoomJoinRequest extends AdditionalDataHolder, Parsable {
    /**
     * The connectionId property
     */
    connectionId?: string | null;
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param RoomCounterUpdated The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRoomCounterUpdated(writer: SerializationWriter, roomCounterUpdated: Partial<RoomCounterUpdated> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!roomCounterUpdated || isSerializingDerivedType) { return; }
    writer.writeObjectValue("counter", roomCounterUpdated.counter);
    writer.writeAdditionalData(roomCounterUpdated.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param RoomCreated The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRoomCreated(writer: SerializationWriter, roomCreated: Partial<RoomCreated> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!roomCreated || isSerializingDerivedType) { return; }
    writer.writeStringValue("id", roomCreated.id);
    writer.writeAdditionalData(roomCreated.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param RoomJoined The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRoomJoined(writer: SerializationWriter, roomJoined: Partial<RoomJoined> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!roomJoined || isSerializingDerivedType) { return; }
    writer.writeObjectValue("counter", roomJoined.counter);
    writer.writeAdditionalData(roomJoined.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param RoomJoinRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRoomJoinRequest(writer: SerializationWriter, roomJoinRequest: Partial<RoomJoinRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!roomJoinRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("connectionId", roomJoinRequest.connectionId);
    writer.writeAdditionalData(roomJoinRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SignalRNegotiation The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSignalRNegotiation(writer: SerializationWriter, signalRNegotiation: Partial<SignalRNegotiation> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!signalRNegotiation || isSerializingDerivedType) { return; }
    writer.writeStringValue("accessToken", signalRNegotiation.accessToken);
    writer.writeStringValue("url", signalRNegotiation.url);
    writer.writeAdditionalData(signalRNegotiation.additionalData);
}
export interface SignalRNegotiation extends AdditionalDataHolder, Parsable {
    /**
     * The accessToken property
     */
    accessToken?: string | null;
    /**
     * The url property
     */
    url?: string | null;
}
/* tslint:enable */
/* eslint-enable */
