// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetApiEngineTurnBasedGameStateData, GetApiEngineTurnBasedGameStateResponses, PostApiEngineTurnBasedGameEndGameData, PostApiEngineTurnBasedGameEndGameResponses, PostApiEngineTurnBasedGameResetData, PostApiEngineTurnBasedGameResetResponses, PostApiEngineTurnBasedGameResolveData, PostApiEngineTurnBasedGameResolveResponses, PostApiEngineTurnBasedGameStartTurnData, PostApiEngineTurnBasedGameStartTurnResponses, PostApiEngineTurnBasedGameSubmitMoveData, PostApiEngineTurnBasedGameSubmitMoveResponses, PostApiRoomsByRoomIdJoinData, PostApiRoomsByRoomIdJoinResponses, PostApiRoomsByRoomIdMouseData, PostApiRoomsByRoomIdMouseResponses, PostApiRoomsData, PostApiRoomsResponses, PostApiSignalrNegotiateData, PostApiSignalrNegotiateResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const postApiEngineTurnBasedGameStartTurn = <ThrowOnError extends boolean = false>(options: Options<PostApiEngineTurnBasedGameStartTurnData, ThrowOnError>) => (options.client ?? client).post<PostApiEngineTurnBasedGameStartTurnResponses, unknown, ThrowOnError>({
    url: '/api/engine/turn-based-game/start-turn',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postApiEngineTurnBasedGameSubmitMove = <ThrowOnError extends boolean = false>(options: Options<PostApiEngineTurnBasedGameSubmitMoveData, ThrowOnError>) => (options.client ?? client).post<PostApiEngineTurnBasedGameSubmitMoveResponses, unknown, ThrowOnError>({
    url: '/api/engine/turn-based-game/submit-move',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postApiEngineTurnBasedGameResolve = <ThrowOnError extends boolean = false>(options: Options<PostApiEngineTurnBasedGameResolveData, ThrowOnError>) => (options.client ?? client).post<PostApiEngineTurnBasedGameResolveResponses, unknown, ThrowOnError>({
    url: '/api/engine/turn-based-game/resolve',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postApiEngineTurnBasedGameEndGame = <ThrowOnError extends boolean = false>(options: Options<PostApiEngineTurnBasedGameEndGameData, ThrowOnError>) => (options.client ?? client).post<PostApiEngineTurnBasedGameEndGameResponses, unknown, ThrowOnError>({
    url: '/api/engine/turn-based-game/end-game',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postApiEngineTurnBasedGameReset = <ThrowOnError extends boolean = false>(options: Options<PostApiEngineTurnBasedGameResetData, ThrowOnError>) => (options.client ?? client).post<PostApiEngineTurnBasedGameResetResponses, unknown, ThrowOnError>({
    url: '/api/engine/turn-based-game/reset',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getApiEngineTurnBasedGameState = <ThrowOnError extends boolean = false>(options?: Options<GetApiEngineTurnBasedGameStateData, ThrowOnError>) => (options?.client ?? client).get<GetApiEngineTurnBasedGameStateResponses, unknown, ThrowOnError>({ url: '/api/engine/turn-based-game/state', ...options });

export const postApiRooms = <ThrowOnError extends boolean = false>(options?: Options<PostApiRoomsData, ThrowOnError>) => (options?.client ?? client).post<PostApiRoomsResponses, unknown, ThrowOnError>({ url: '/api/rooms', ...options });

export const postApiRoomsByRoomIdJoin = <ThrowOnError extends boolean = false>(options: Options<PostApiRoomsByRoomIdJoinData, ThrowOnError>) => (options.client ?? client).post<PostApiRoomsByRoomIdJoinResponses, unknown, ThrowOnError>({
    url: '/api/rooms/{roomId}/join',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postApiRoomsByRoomIdMouse = <ThrowOnError extends boolean = false>(options: Options<PostApiRoomsByRoomIdMouseData, ThrowOnError>) => (options.client ?? client).post<PostApiRoomsByRoomIdMouseResponses, unknown, ThrowOnError>({
    url: '/api/rooms/{roomId}/mouse',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postApiSignalrNegotiate = <ThrowOnError extends boolean = false>(options?: Options<PostApiSignalrNegotiateData, ThrowOnError>) => (options?.client ?? client).post<PostApiSignalrNegotiateResponses, unknown, ThrowOnError>({ url: '/api/signalr/negotiate', ...options });
