// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { PostApiRoomsByRoomIdIncrementData, PostApiRoomsByRoomIdIncrementResponses, PostApiRoomsByRoomIdJoinData, PostApiRoomsByRoomIdJoinResponses, PostApiRoomsData, PostApiRoomsResponses, PostApiSignalrNegotiateData, PostApiSignalrNegotiateResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const postApiRooms = <ThrowOnError extends boolean = false>(options?: Options<PostApiRoomsData, ThrowOnError>) => (options?.client ?? client).post<PostApiRoomsResponses, unknown, ThrowOnError>({ url: '/api/rooms', ...options });

export const postApiRoomsByRoomIdJoin = <ThrowOnError extends boolean = false>(options: Options<PostApiRoomsByRoomIdJoinData, ThrowOnError>) => (options.client ?? client).post<PostApiRoomsByRoomIdJoinResponses, unknown, ThrowOnError>({
    url: '/api/rooms/{roomId}/join',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postApiRoomsByRoomIdIncrement = <ThrowOnError extends boolean = false>(options: Options<PostApiRoomsByRoomIdIncrementData, ThrowOnError>) => (options.client ?? client).post<PostApiRoomsByRoomIdIncrementResponses, unknown, ThrowOnError>({ url: '/api/rooms/{roomId}/increment', ...options });

export const postApiSignalrNegotiate = <ThrowOnError extends boolean = false>(options?: Options<PostApiSignalrNegotiateData, ThrowOnError>) => (options?.client ?? client).post<PostApiSignalrNegotiateResponses, unknown, ThrowOnError>({ url: '/api/signalr/negotiate', ...options });
