// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type MousePresenceUpdate = {
    playerNumber: number | string;
    name: string;
    x: number | string;
    y: number | string;
};

export type RoomCreated = {
    id: string;
};

export type RoomJoined = {
    player: RoomPlayer;
    players: Array<RoomPlayer>;
};

export type RoomJoinRequest = {
    connectionId: string;
    name: string;
    playerNumber: null | number | string;
};

export type RoomPlayer = {
    number: number | string;
    name: string;
};

export type SignalRNegotiation = {
    url: string;
    accessToken: string;
};

export type PostApiRoomsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/rooms';
};

export type PostApiRoomsResponses = {
    /**
     * OK
     */
    200: RoomCreated;
};

export type PostApiRoomsResponse = PostApiRoomsResponses[keyof PostApiRoomsResponses];

export type PostApiRoomsByRoomIdJoinData = {
    body: RoomJoinRequest;
    path: {
        roomId: string;
    };
    query?: never;
    url: '/api/rooms/{roomId}/join';
};

export type PostApiRoomsByRoomIdJoinResponses = {
    /**
     * OK
     */
    200: RoomJoined;
};

export type PostApiRoomsByRoomIdJoinResponse = PostApiRoomsByRoomIdJoinResponses[keyof PostApiRoomsByRoomIdJoinResponses];

export type PostApiRoomsByRoomIdMouseData = {
    body: MousePresenceUpdate;
    path: {
        roomId: string;
    };
    query?: never;
    url: '/api/rooms/{roomId}/mouse';
};

export type PostApiRoomsByRoomIdMouseResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiSignalrNegotiateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/signalr/negotiate';
};

export type PostApiSignalrNegotiateResponses = {
    /**
     * OK
     */
    200: SignalRNegotiation;
};

export type PostApiSignalrNegotiateResponse = PostApiSignalrNegotiateResponses[keyof PostApiSignalrNegotiateResponses];
