// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type RoomCounterUpdated = {
    counter: number | string;
};

export type RoomCreated = {
    id: string;
};

export type RoomJoined = {
    counter: number | string;
};

export type RoomJoinRequest = {
    connectionId: string;
};

export type SignalRNegotiation = {
    url: string;
    accessToken: string;
};

export type PostApiRoomsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/rooms';
};

export type PostApiRoomsResponses = {
    /**
     * OK
     */
    200: RoomCreated;
};

export type PostApiRoomsResponse = PostApiRoomsResponses[keyof PostApiRoomsResponses];

export type PostApiRoomsByRoomIdJoinData = {
    body: RoomJoinRequest;
    path: {
        roomId: string;
    };
    query?: never;
    url: '/api/rooms/{roomId}/join';
};

export type PostApiRoomsByRoomIdJoinResponses = {
    /**
     * OK
     */
    200: RoomJoined;
};

export type PostApiRoomsByRoomIdJoinResponse = PostApiRoomsByRoomIdJoinResponses[keyof PostApiRoomsByRoomIdJoinResponses];

export type PostApiRoomsByRoomIdIncrementData = {
    body?: never;
    path: {
        roomId: string;
    };
    query?: never;
    url: '/api/rooms/{roomId}/increment';
};

export type PostApiRoomsByRoomIdIncrementResponses = {
    /**
     * OK
     */
    200: RoomCounterUpdated;
};

export type PostApiRoomsByRoomIdIncrementResponse = PostApiRoomsByRoomIdIncrementResponses[keyof PostApiRoomsByRoomIdIncrementResponses];

export type PostApiSignalrNegotiateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/signalr/negotiate';
};

export type PostApiSignalrNegotiateResponses = {
    /**
     * OK
     */
    200: SignalRNegotiation;
};

export type PostApiSignalrNegotiateResponse = PostApiSignalrNegotiateResponses[keyof PostApiSignalrNegotiateResponses];
