/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createSignalRNegotiationFromDiscriminatorValue, type SignalRNegotiation } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/signalr/negotiate
 */
export interface NegotiateRequestBuilder extends BaseRequestBuilder<NegotiateRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SignalRNegotiation>}
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SignalRNegotiation | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const NegotiateRequestBuilderUriTemplate = "{+baseurl}/api/signalr/negotiate";
/**
 * Metadata for all the requests in the request builder.
 */
export const NegotiateRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: NegotiateRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createSignalRNegotiationFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
