@Server_HostAddress = http://localhost:5407

POST {{Server_HostAddress}}/api/rooms
Accept: application/json

### Start Game

POST {{Server_HostAddress}}/api/engine/turn-based-game/start-game
Content-Type: application/json
Accept: application/json

{
  "playerId": "player-1"
}

### Start Turn

POST {{Server_HostAddress}}/api/engine/turn-based-game/start-turn
Content-Type: application/json
Accept: application/json

{
  "gameId": "c8bdae2af70241efb0aa960eba853680",
  "playerId": "player-2"
}

### Stop Game

POST {{Server_HostAddress}}/api/engine/turn-based-game/stop-game
Content-Type: application/json
Accept: application/json

{
  "gameId": "c8bdae2af70241efb0aa960eba853680",
  "playerId": "player-1"
}

### Make Move

POST {{Server_HostAddress}}/api/engine/turn-based-game/make-move
Content-Type: application/json
Accept: application/json

{
  "gameId": "c8bdae2af70241efb0aa960eba853680",
  "playerId": "player-2",
  "movePayload": "attack:slot-2"
}