/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { NegotiateRequestBuilderRequestsMetadata, type NegotiateRequestBuilder } from './negotiate/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/signalr
 */
export interface SignalrRequestBuilder extends BaseRequestBuilder<SignalrRequestBuilder> {
    /**
     * The negotiate property
     */
    get negotiate(): NegotiateRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const SignalrRequestBuilderUriTemplate = "{+baseurl}/api/signalr";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const SignalrRequestBuilderNavigationMetadata: Record<Exclude<keyof SignalrRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    negotiate: {
        requestsMetadata: NegotiateRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
