/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createRoomJoinedFromDiscriminatorValue, serializeRoomJoined, serializeRoomJoinRequest, type RoomJoined, type RoomJoinRequest } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/rooms/{roomId}/join
 */
export interface JoinRequestBuilder extends BaseRequestBuilder<JoinRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<RoomJoined>}
     */
     post(body: RoomJoinRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<RoomJoined | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: RoomJoinRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const JoinRequestBuilderUriTemplate = "{+baseurl}/api/rooms/{roomId}/join";
/**
 * Metadata for all the requests in the request builder.
 */
export const JoinRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: JoinRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createRoomJoinedFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeRoomJoinRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
