/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createRoomCounterUpdatedFromDiscriminatorValue, type RoomCounterUpdated } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/rooms/{roomId}/increment
 */
export interface IncrementRequestBuilder extends BaseRequestBuilder<IncrementRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<RoomCounterUpdated>}
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<RoomCounterUpdated | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const IncrementRequestBuilderUriTemplate = "{+baseurl}/api/rooms/{roomId}/increment";
/**
 * Metadata for all the requests in the request builder.
 */
export const IncrementRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: IncrementRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createRoomCounterUpdatedFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
