/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { IncrementRequestBuilderRequestsMetadata, type IncrementRequestBuilder } from './increment/index.js';
// @ts-ignore
import { JoinRequestBuilderRequestsMetadata, type JoinRequestBuilder } from './join/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/rooms/{roomId}
 */
export interface WithRoomItemRequestBuilder extends BaseRequestBuilder<WithRoomItemRequestBuilder> {
    /**
     * The increment property
     */
    get increment(): IncrementRequestBuilder;
    /**
     * The join property
     */
    get join(): JoinRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithRoomItemRequestBuilderUriTemplate = "{+baseurl}/api/rooms/{roomId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithRoomItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithRoomItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    increment: {
        requestsMetadata: IncrementRequestBuilderRequestsMetadata,
    },
    join: {
        requestsMetadata: JoinRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
