import fs from 'node:fs/promises'
import path from 'node:path'

// I know what you're thinking... what the heck, Tyler.
// It's cheaper than pulling in a library and isn't that much code at all.
// It takes the exact form I want I don't have to adopt any proprietary formats.
// It's only brittle if you break it! 😅

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..')
const eventsCsPath = path.resolve(root, '../HouseParty.GameEngine/Models/Events.cs')
const outPath = path.resolve(root, 'src/generated/events.ts')

function toCamelCase(name) {
  return name.charAt(0).toLowerCase() + name.slice(1)
}

function mapType(csType) {
  switch (csType) {
    case 'string':
      return 'string'
    case 'long':
    case 'int':
      return 'number'
    case 'bool':
      return 'boolean'
    default:
      return 'unknown'
  }
}

function parseParams(raw) {
  const trimmed = raw.trim()
  if (!trimmed) return []

  return trimmed
    .split(',')
    .map((part) => part.trim())
    .filter(Boolean)
    .map((part) => {
      const [csType, csName] = part.split(/\s+/)
      return {
        csType,
        csName,
        tsName: toCamelCase(csName),
        tsType: mapType(csType),
      }
    })
}

function renderEventType(recordName, params) {
  const fieldLines = params.map((p) => `  ${p.tsName}: ${p.tsType}`).join('\n')
  return `export type ${recordName} = GameEventBase & {\n  name: '${recordName}'\n${fieldLines ? `${fieldLines ? `\n${fieldLines}` : ''}` : ''}\n}`
}

function renderFieldSchema(params) {
  if (params.length === 0) {
    return '[]'
  }

  return `[\n${params
    .map((p) => `    { name: '${p.tsName}', type: '${p.tsType}' }`)
    .join(',\n')}\n  ]`
}

function toObjectLockEffect(recordName, params) {
  const hasObjectId = params.some((p) => p.tsName === 'objectId')
  if (!hasObjectId) {
    return 'none'
  }

  if (recordName.startsWith('Control')) {
    return 'acquire'
  }

  if (recordName.startsWith('Release') || recordName.startsWith('Revoke')) {
    return 'release'
  }

  return 'none'
}

const source = await fs.readFile(eventsCsPath, 'utf8')
const recordRegex = /public sealed record (\w+)\s*(?:\(([^)]*)\))?\s*:\s*GameEvent/g

const matches = []
for (const match of source.matchAll(recordRegex)) {
  const recordName = match[1]
  const rawParams = match[2] ?? ''
  matches.push({ recordName, params: parseParams(rawParams) })
}

if (matches.length === 0) {
  throw new Error(`No GameEvent records found in ${eventsCsPath}`)
}

const header = `// AUTO-GENERATED FILE. DO NOT EDIT.\n// Generated by scripts/gen-events.mjs from HouseParty.GameEngine/Models/Events.cs\n\n`
const base = `export type GameEventBase = {\n  sequence: number\n  name: string\n  playerId: string\n  timestamp: number\n  $type?: string\n}\n\n`
const typeBlocks = matches.map(({ recordName, params }) => renderEventType(recordName, params)).join('\n\n')
const metadata = `\n\nexport type EventFieldSchema = {\n  name: string\n  type: 'string' | 'number' | 'boolean' | 'unknown'\n}\n\nexport type EventSchema = {\n  name: GameEventName\n  fields: readonly EventFieldSchema[]\n  objectLockEffect: 'none' | 'acquire' | 'release'\n}\n\nexport const GAME_EVENT_SCHEMAS: readonly EventSchema[] = [\n${matches
  .map(
    ({ recordName, params }) =>
      `  {\n    name: '${recordName}',\n    fields: ${renderFieldSchema(params)},\n    objectLockEffect: '${toObjectLockEffect(recordName, params)}',\n  }`,
  )
  .join(',\n')}\n] as const\n`
const union = `\n\nexport type GameEvent =\n${matches.map(({ recordName }) => `  | ${recordName}`).join('\n')}\n\nexport type GameEventName = GameEvent['name']\n\nexport type GameObjectLock = {\n  objectId: string\n  holderPlayerId: string | null\n}\n`

await fs.writeFile(outPath, `${header}${base}${typeBlocks}${union}${metadata}`)
console.log(`Generated ${path.relative(process.cwd(), outPath)}`)
